# A name for our Workflow
name: Build and Deploy React App

# Specifies that the workflow should be triggered on a Git push event.
on:
    push:
        branches:
            #Specifies the branches on which the workflow should be triggered
            - main

#Defines the jobs to be executed as part of the workflow
jobs:
    #The name of the job, in this case, "CI-CD."
    CI-CD:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
            - uses: actions/checkout@v4
          
            -name: Print hello
            run: echo hai
