name: 'Deploy website on push'

on:
    push:
        branches:
            - main
jobs:
    start:
        name: Greet
        runs-on: ubuntu-latest

        steps:
            -name: Print hello
            run: echo hai
