name: Build and Deploy React App
on:
    push:
        branches:
            - main

jobs:
    CI-CD:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
          
            - name: Print hello
              run: echo hai
