name: Build and Deploy React App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print hello
        run: echo hai
      
      - name: View PWD
        run: pwd
      
      - name: View Files
        run: ls -al




